---
apiVersion: templates.krateo.io/v1alpha1
kind: aws-stack
metadata:
  name: krateo-aws-stack
spec:
  compositionSelector:
    matchLabels:
      platform: aws
  eks:
    clusterName: #ex clusterRef
  name: #values.component_id
  network:
    networkName: #ex networkRef spec.network.name
  rds:
    rdsRegion:
    rdsDataDiskSizeGb:
    rdsInstanceClass:
    rdsEngineVersion:
    rdsStorageType:
  fromRepo:
    domain: github.com
    provider: github
    apiUrl: https://api.github.com/
    repositoryName: krateo-template-sample
    organizationName: krateoplatformops
  toRepo:
    domain: "${{ domain }}"
    provider: "${{ provider }}"
    apiUrl: https://api.github.com/
    repositoryName: "${{ repositoryName }}"
    organizationName: "${{ organizationName }}"

  