---
apiVersion: templates.krateo.io/v1alpha1
kind: aws-stack
metadata:
  name: krateo-aws-stack
spec:
  compositionSelector:
    matchLabels:
      platform: aws
  clusterName: #ex clusterRef
  component_id: #values.component_id
  networkName: #ex networkRef spec.network.name
  rds:
    rdsRegion:
    rdsDataDiskSizeGb:
    rdsInstanceClass:
    rdsEngineVersion:
    rdsStorageType:
    

  