apiVersion: dashboard.krateo.io/v1alpha1
kind: Deployment
metadata:
  name: ${{ name }}
  description: ${{ description }}
  icon: "fa-brands fa-aws"
  tags:
    - aws
    - stack
    - infrastructure
    - rds
  links:
    - url: https://${{ provider }}/${{ organizationName }}/${{ repositoryName }}
      title: ${{ organizationName }}/${{ repositoryName }}
      icon: "fa-brands fa-git"
    - url: https://kiratech.awsapps.com/start#/
      title: AWS Console
      icon: "fa-brands fa-aws"
  plugins:
    - name: resources
      value: ${{ organizationName }}-${{ repositoryName }}
spec:
  owner: ${{ owner }}
